language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "OoCwPczrLW9Batso5eOrbRpTAn/2VuNT/VHj70IORuuWX0pN9Fth5QrKLBREN8NqdUVeTRI25izQZuryHyANB8fH4Xt+p49Tnpd7Pwyv+CxD35cFl6S6a3X/cWw80vYNo1PVSzUnLf702PY06lYJzWQkJ5NfO/zDmNRiz5Rx/bA="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
