language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "I+Ej+OwAadmMaGRE3XgnO3Vpb/+7/nKAa5/3yvVWZxDL7VW9XMlLpuoy4iTAIZEdsymfIiuKp9xdlLaZ07As7DocmKO7z6x8oYvg2svkUSfFzEaPKKqOZ6ZaIi+5m/lIpzoIxZvYl8qEvAc2XV1l63bp++472RJniFCVgDNh6/Y="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
